version: "3.9"
services:
  postgres:
    image: postgres:latest # Use the desired PostgreSQL version
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Map the default PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
